print('8 == 8:',8 == 8)
print('8 != 8:',8 != 8)
print('2 < 0:',2 < 0)
print('2 <= 2:',2 <= 2)
print('hello == hello:','hello' == 'hello')
print('hello == Hello:','hello'== 'Hello')
print('1 True and True > ' ,True and True)
print('2 True and False > ',True and False)
print('3 True or False > ',True or False)
print('4 False or False > ',False or False)
print('5 not True > ',not True)
print('6 not False > ',not False)